"""add_audio_and_play_tables_and_relations

Revision ID: 1b81127b90e0
Revises: 7f78b849831c
Create Date: 2025-06-09 21:17:28.531880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b81127b90e0'
down_revision: Union[str, None] = '7f78b849831c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands for audios table ###
    op.create_table('audios',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('book_id', sa.String(), nullable=False),
        sa.Column('chapter_index', sa.Integer(), nullable=False),
        sa.Column('audio_path', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audios_id'), 'audios', ['id'], unique=False)
    op.create_index(op.f('ix_audios_book_id'), 'audios', ['book_id'], unique=False) # Index for FK

    # ### commands for plays table ###
    op.create_table('plays',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('book_id', sa.String(), nullable=False),
        sa.Column('audio_id', sa.String(), nullable=False),
        sa.Column('last_timestamp', sa.Float(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True), # Allow nullable for created_at behavior, or set server_default
        # created_at is not explicitly in the model but useful (handled by default=datetime.utcnow)
        # sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    op.create_index(op.f('ix_plays_user_id'), 'plays', ['user_id'], unique=False) # Index for FK
    op.create_index(op.f('ix_plays_book_id'), 'plays', ['book_id'], unique=False) # Index for FK
    op.create_index(op.f('ix_plays_audio_id'), 'plays', ['audio_id'], unique=False) # Index for FK
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plays_audio_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_book_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_user_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')

    op.drop_index(op.f('ix_audios_book_id'), table_name='audios')
    op.drop_index(op.f('ix_audios_id'), table_name='audios')
    op.drop_table('audios')
    # ### end Alembic commands ###
